name: Python Run Example

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies (skip if requirements.txt missing or empty)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No dependencies to install."
          fi

      - name: Run nbn.py
        run: python nbn.py
